thirdandgrove/thirdandgrove-com-gatsby

src/components/ContentBody/Text.js
src/components/ContentBody/TextImage.js

added link styles for content body text components

---

src/pages/about.js

updated founding year and refs to oakland

---

yarn.lock

Reverts thirdandgrove/thirdandgrove-com-gatsby#341

Revert "upgraded packages"

---

src/components/WhatWeDo/WhatWeDo.js
src/pages/index.js

added requested text to homepage

---

src/templates/insights.js

handles error that happens in preview when content is being created.

safety check for Image src in insights template

---

src/pages/about.js

Update titles
- https://thirdandgrove.atlassian.net/browse/SWAT-1743
- https://thirdandgrove.atlassian.net/browse/SWAT-1762

SWAT-1743 SWAT-1762 Update titles

---

src/components/seo.js

Window was not defined on server image was never set. 
This removes the check for window and sets base url.
- https://thirdandgrove.atlassian.net/browse/SWAT-1763

Fix social images

---

src/components/ArticlePreview/ArticlePreview.js
src/components/ArticlePreviewSlide/ArticlePreviewSlide.js
src/components/NewsletterForm/NewsletterForm.js
src/components/seo.js
src/templates/insights.js

https://thirdandgrove.atlassian.net/browse/T5-200﻿

 T5-200 Add google optimize script

---

src/pages/about.js

https://thirdandgrove.atlassian.net/browse/T5-217

T5-217 Remove restaurant names and update tag line

---

src/pages/about.js

https://thirdandgrove.atlassian.net/browse/T5-218

T5-218 Add Boston link

---

gatsby-config.js
package.json
yarn.lock

[T5-246](https://thirdandgrove.atlassian.net/browse/T5-246)
[T5-248](https://thirdandgrove.atlassian.net/browse/T5-248)

T5-246 Adjust robots.txt

---

gatsby-config.js

https://thirdandgrove.atlassian.net/browse/T5-246?focusedCommentId=114344﻿

T5-246 Disallow any url with /career

---

gatsby-config.js

https://thirdandgrove.atlassian.net/browse/T5-263﻿

T5-263 Return string of production

---

src/components/ContentBody/ContentBody.js
src/components/ContentBody/Video.js
src/templates/insights.js
src/templates/studies.js

Adds a video component that can be used with Case studies and Insights.

T5-265 Add and style video component

---

src/pages/drupalcon-2021-event.js
static/functions/submission-created.js

T5-279 Update data destructuring

---

src/templates/studies.js

https://thirdandgrove.atlassian.net/browse/T5-282

T5-282 Add new meta fields

---

src/components/ArticlePreviewSlide/ArticlePreviewSlide.js
src/pages/index.js

- Remove attribution from insights slide

T5-284 gated insight

---

gatsby-config.js
package.json
yarn.lock

https://thirdandgrove.atlassian.net/browse/T5-286

T5-286 Remove react axe plugin

---

package.json
src/components/ContentBody/ContentBody.js
src/components/ContentBody/Text.js
src/components/ContentBody/TextImage.js
src/components/ContentBody/TextVideoPhone.js
src/templates/insights.js
src/util/index.js
yarn.lock

https://thirdandgrove.atlassian.net/browse/T5-283

T5-283 Add target blank external links

---

package.json
src/components/ContentBody/ContentBody.js
src/components/ContentBody/Text.js
src/components/ContentBody/TextImage.js
src/components/ContentBody/TextVideoPhone.js
src/templates/insights.js
src/util/index.js
yarn.lock

Reverts thirdandgrove/thirdandgrove-com-gatsby#449

Revert "T5-283 Add target blank external links"

---

static/functions/submission-created.js

Expected to find one of the known reducer keys instead:

T5-294 Add contact forms to Klayvio

---

src/components/VideoSection/VideoSection.js

https://thirdandgrove.atlassian.net/browse/T5-295

T5-295 Fix site bug video work page

---

src/templates/insights.js
src/templates/legacyInsights.js
src/templates/studies.js
src/util/index.js

https://thirdandgrove.atlassian.net/browse/T5-283

T5-238 Update external links to open in a new tab

---

src/pages/index.js

Use this to power the home page case studies slider `/admin/structure/entityqueue/case_study_slider_homepage/case_study_slider_homepage?destination=/admin/structure/entityqueue`

add-home-case-studies-entity-queue: Add Entity Queue with homepage specific slider list

---

src/pages/partners/shopify.js

https://thirdandgrove.atlassian.net/browse/T5-318

T5-318 Add link for badlands

---

package.json
src/components/ContentBody/PostCode.js
src/components/ContentBody/Text.js
src/components/ContentBody/Video.js
yarn.lock

https://thirdandgrove.atlassian.net/browse/T5-331

T5-331 Add code highlighting

---

schema.gql
src/components/ContentBody/Text.js
src/templates/insights.js

https://thirdandgrove.atlassian.net/browse/T5-351

T5-351: integrate field capital letter

---

src/components/Menu/Menu.js

https://thirdandgrove.atlassian.net/browse/T5-400

T5-400: make menu mobile scroll

---

src/components/ContentBody/Video.js

https://thirdandgrove.atlassian.net/browse/T5-333

T5-333: fix video component

---

schema.gql
src/templates/studies.js

https://thirdandgrove.atlassian.net/browse/T5-410

T5-410: stats component for case studies

---

schema.gql
src/components/CapabilitiesSlider/CapabilitiesSlide.json
src/components/ContentBody/ContentBody.js
src/components/ContentBody/CoreValues.js
src/components/ContentBody/FullWidthVideo.js
src/components/ContentBody/Hero.js
src/components/ContentBody/ScrollingLogos.js
src/components/LogoGrid/LogoGridSlider.js
src/components/LogoGrid/logosets.js
src/components/VideoSection/VideoSection.js
src/pages/work.js
src/templates/landings.js

https://thirdandgrove.atlassian.net/browse/T5-411

T5-411: create core values component

---

schema.gql
src/components/ContentBody/Stats.js
src/templates/landings.js

https://thirdandgrove.atlassian.net/browse/T5-414

T5-414: add media background to stats

---

src/components/Menu/Menu.js
src/components/layout.js

https://thirdandgrove.atlassian.net/browse/T5-421

T5-421: Add hover state to main nav heading

---

src/components/Menu/Menu.js
src/components/layout.js

Reverts thirdandgrove/thirdandgrove-com-gatsby#605

Revert "T5-421: Add hover state to main nav heading"

---

src/components/TopNav/TopNav.js

this PR will fix this hyrdation error that is in prod.
```
Uncaught Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

T5-0 Fix hydration error

---

netlify/functions/submission-created.js
src/components/Footer/Footer.js
src/components/Form/Form.js
src/components/Menu/Menu.js
yarn.lock

This PR will add recaptcha back to our contact form

T5-0 Add recaptcha back to forms

---

package.json
src/styles/globalStyles.js

Adding Media Query to apply left padding for the desktop version (to fix overlap of numbers/list).

[T5-441] Adding Media Query to apply left padding for the desktop version (to fix overlap of numbers/list).

---

src/components/ContentBody/ServicesComponent.js

Adding logic to add margin-top to second component section, when field_primary_cta field is not null (in order to distinguish pages).

[T5-432] Adding logic to add margin-top to second component section, when field_primary_cta field is not null (in order to distinguish pages).

---

src/pages/index.js

https://thirdandgrove.atlassian.net/browse/T5-458

Remove extra space in homepage hero headline 
